language: php

env:
    global:
        - setup=stable

matrix:
    fast_finish: true
    include:
        - php: 7.3
        - php: 7.3
          env: setup=lowest
        - php: 7.4
        - php: 7.4
          env: setup=lowest

sudo: false

before_install:
    - travis_retry composer self-update

install:
    - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
    - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit